name: MinecraftBot
author: Rafa652
version: 2.2.3
description: Simple IRC and Minecraft integration.
main: com.avisenera.minecraftbot.MinecraftBot
commands:
    names:
        description: Displays the users on the IRC channel
        usage: /names
    n:
        description: Displays the users on the IRC channel
        usage: /n
    irc:
        description: Does a given action on IRC
        usage: /irc say|do|op|deop|voice|devoice|kick|ban|unban
        permission: minecraftbot.op
        permission-message: '[MinecraftBot] You are not allowed to use this command.'
    minecraftbot:
        description: Manages the plugin and IRC connection
        usage: /minecraftbot connect|disconnect|join|part|reload
        permission: minecraftbot.manage
        permission-message: '[MinecraftBot] You are not allowed to use this command.'
permissions:
    minecraftbot.op:
        description: Allows use of the /irc command. Equivalent to having +o in IRC.
    minecraftbot.manage:
        description: Allows use of the /minecraftbot command as well as the /irc command.
        children:
            minecraftbot.op: true
    minecraftbot.*:
        description: Gives access to all plugin commands. Equivalent to minecraftbot.manage
        children:
            minecraftbot.op: true
            minecraftbot.manage: true